trigger:
  branches:
    include:
      - main
  paths:
    include:
      - vumatel-terragrunt/terragrunt/b2c/accounts/vumatel-b2c-preprod/*
pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  - template: ./azure-pipeline-vars.yml

stages:
  - template: /templates/terragrunt-deploy@pipelines
    parameters:
      project_name: ${{variables.project_name}}
      repo_id: ${{variables.repo_id}}
      directory:  ${{variables.directory}}
